module.exports = {
  docs: [
    {
      type: "category",
      label: "핵심 개념 (ERA)",
      collapsed: false,
      items: [
        "what-is-datahub/datahub-concepts",
        "what/entity",
        "what/aspect",
        "what/relationship",
        "what/urn",
        "what/mxe",
        "modeling/metadata-model",
        "modeling/extending-the-metadata-model",
      ],
    },
    {
      type: "category",
      label: "아키텍처",
      items: [
        "architecture/architecture",
        "architecture/metadata-ingestion",
        "architecture/metadata-serving",
      ],
    },
    {
      type: "category",
      label: "Lineage (데이터 계보)",
      items: [
        "features/feature-guides/lineage",
        "features/feature-guides/ui-lineage",
        "lineage/sql_parsing",
        "api/tutorials/lineage",
        "act-on-metadata/impact-analysis",
        "ingestion/docs/sources/file-based-lineage/README",
        "integration/java/acryl-spark-lineage/README",
      ],
    },
    {
      type: "category",
      label: "Data Quality / Assertions",
      items: [
        "managed-datahub/observe/assertions",
        "managed-datahub/observe/freshness-assertions",
        "managed-datahub/observe/volume-assertions",
        "managed-datahub/observe/column-assertions",
        "managed-datahub/observe/schema-assertions",
        "managed-datahub/observe/custom-sql-assertions",
        "managed-datahub/observe/smart-assertions",
        "managed-datahub/observe/data-health-dashboard",
        "managed-datahub/observe/data-contract",
        "managed-datahub/observe/assertion-backfill",
        "managed-datahub/observe/assertion-notes",
        "managed-datahub/observe/assertion-query-attribution",
        "assertions/open-assertions-spec",
        "api/tutorials/assertions",
        "api/tutorials/custom-assertions",
        "api/tutorials/sdk/bulk-assertions-sdk",
        "api/tutorials/data-contracts",
        "advanced/monitoring",
      ],
    },
    {
      type: "category",
      label: "Ingestion (데이터 수집)",
      items: [
        "ingestion/README",
        "ingestion/recipe_overview",
        "ingestion/source_overview",
        "ingestion/sink_overview",
        "ingestion/cli-ingestion",
        "ingestion/adding-source",
        "ui-ingestion",
        "metadata-ingestion-security",
        {
          type: "category",
          label: "스케줄링",
          items: [
            "ingestion/schedule_docs/intro",
            "ingestion/schedule_docs/cron",
            "ingestion/schedule_docs/airflow",
            "ingestion/schedule_docs/kubernetes",
          ],
        },
        "ingestion/KAFKA_CONNECT_LINEAGE",
        "ingestion/integration_docs/great-expectations",
        "ingestion/docs/dev_guides/sql_profiles",
        "ingestion/docs/sources/dbt/README",
        {
          type: "category",
          label: "Transformer",
          items: [
            "ingestion/docs/transformer/intro",
            "ingestion/docs/transformer/dataset_transformer",
            "ingestion/docs/transformer/universal_transformers",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "SDK / API",
      items: [
        "api/datahub-apis",
        {
          type: "category",
          label: "Python SDK",
          items: [
            "ingestion/as-a-library",
            "api/tutorials/datasets",
            "api/tutorials/descriptions",
            "api/tutorials/sdk/search_client",
            "ingestion/developing",
            "ingestion/examples/library/README",
          ],
        },
        {
          type: "category",
          label: "Java SDK",
          items: [
            "integration/java/as-a-library",
            "integration/java/as-a-library-v2",
            "integration/java/docs/sdk-v2/getting-started",
            "integration/java/docs/sdk-v2/design-principles",
            "integration/java/docs/sdk-v2/client",
            "integration/java/docs/sdk-v2/entities-overview",
            "integration/java/docs/sdk-v2/migration-from-v1",
            "integration/java/docs/sdk-v2/patch-operations",
            "integration/java/docs/sdk-v2/dataset-entity",
            "integration/java/docs/sdk-v2/dataflow-entity",
            "integration/java/docs/sdk-v2/datajob-entity",
            "integration/java/docs/sdk-v2/dashboard-entity",
            "integration/java/docs/sdk-v2/chart-entity",
            "integration/java/docs/sdk-v2/container-entity",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "MLModel",
      items: [
        "api/tutorials/mlmodel-mlmodelgroup",
        "api/tutorials/ml",
        "integration/java/docs/sdk-v2/mlmodel-entity",
        "integration/java/docs/sdk-v2/mlmodelgroup-entity",
      ],
    },
    {
      type: "category",
      label: "Ownership / Tags / Glossary",
      items: [
        "ownership/ownership-types",
        "api/tutorials/owners",
        "tags",
        "api/tutorials/tags",
        "glossary/business-glossary",
        "api/tutorials/terms",
      ],
    },
    {
      type: "category",
      label: "고급 주제",
      items: [
        "advanced/mcp-mcl",
        "advanced/writing-mcps",
        "advanced/bootstrap-mcps",
        "advanced/aspect-versioning",
        "advanced/derived-aspects",
        "advanced/entity-hierarchy",
        "advanced/partial-update",
        "advanced/patch",
        "advanced/pdl-best-practices",
        "how/add-new-aspect",
        "schema-history",
      ],
    },
    {
      type: "category",
      label: "학습 자료",
      items: [
        "learn/data-freshness",
        "learn/data-pipeline",
        "learn/business-metric",
        "learn/business-glossary",
        "learn/data-mesh",
      ],
    },
  ],
};
